const images = {
  logo: require("../assets/images/logo.png"),
  logo2: require("../assets/images/logo-2.png"),
  logo3: require("../assets/images/logo-3.png"),
  hero: require("../assets/images/hero.png"),
  placeholder: require("../assets/images/placeholder.png"),
  placeholder1: require("../assets/images/placeholder-1.png"),
  placeholder2: require("../assets/images/placeholder-2.png"),
  placeholder3: require("../assets/images/placeholder-3.png"),
  placeholder4: require("../assets/images/placeholder-4.png"),
  placeholder5: require("../assets/images/placeholder-5.png"),
  placeholder6: require("../assets/images/placeholder-6.png"),
  rectangle: require("../assets/images/rectangle.svg"),
  rectangle1: require("../assets/images/rectangle-1.svg"),
  rectangle2: require("../assets/images/rectangle-2.svg"),
  howItWorks1: require("../assets/images/how-it-works-1.svg"),
  howItWorks2: require("../assets/images/how-it-works-2.svg"),
  howItWorks3: require("../assets/images/how-it-works-3.svg"),
  howItWorks4: require("../assets/images/how-it-works-4.svg"),
  plusSign: require("../assets/images/plus-sign.svg"),
  plusSign2: require("../assets/images/plus-sign-2.svg"),
  equalsSign: require("../assets/images/equals-sign.svg"),
  videoIcon: require("../assets/images/video-icon.svg"),
  videoIcon2: require("../assets/images/video-icon-2.svg"),
  videoIcon3: require("../assets/images/video-icon-3.svg"),
  videoIcon4: require("../assets/images/video-icon-4.svg"),
  videoIcon5: require("../assets/images/video-icon-5.svg"),
  videoIcon6: require("../assets/images/video-icon-6.svg"),
  videoIcon7: require("../assets/images/video-icon-7.svg"),
  paymentOptions: require("../assets/images/payment-options.png"),
  andoidIcon: require("../assets/images/android.svg"),
  appleIcon: require("../assets/images/apple-icon.svg"),
  greenMask: require("../assets/images/green-mask.png"),
  pinkMask: require("../assets/images/pink-mask.png"),
  downIcon: require("../assets/images/down-icon.png"),
  userImage: require("../assets/images/userimage.png"),
  qrCode: require("../assets/images/qrcode.png"),
  userImageBig: require("../assets/images/userimagebig.png"),
  user2image: require("../assets/images/user2image.png"),
  teacher1: require("../assets/images/teacher1.png"),
  teacher2: require("../assets/images/teacher2.png"),
};

export default images;
